"""Hard-coded chemistry data for the Tsuda 1989 Ni(0)/pyridyl-phosphine pyrone paper.

Tsuda, Morikawa, Saegusa, J. Chem. Soc. Chem. Commun. 1989, 9.
"""
from __future__ import annotations
from typing import Any

PAPER_COMPOUND_TABLE: list[dict[str, Any]] = [
    {"paper_id": '1a', "role": 'ligand',
     "name": "1-(2'-pyridyl)-2-(di-n-butylphosphino)ethane",
     "fallback_smiles": 'CCCCP(CCCC)CCc1ccccn1'},
    {"paper_id": '1b', "role": 'ligand',
     "name": '(2-pyridylmethyl)di-n-butylphosphine',
     "fallback_smiles": 'CCCCP(CCCC)Cc1ccccn1'},
    {"paper_id": '2a', "role": 'diyne',
     "name": 'hepta-1,6-diyne (Z = CH2, R = H)',
     "fallback_smiles": 'C#CCCCC#C'},
    {"paper_id": '2b', "role": 'diyne',
     "name": 'octa-1,7-diyne (Z = CH2CH2, R = H)',
     "fallback_smiles": 'C#CCCCCC#C'},
    {"paper_id": '2c', "role": 'diyne',
     "name": '9-methyl-deca-1,8-diyne (Z = CH2CH2, R = iPr)',
     "fallback_smiles": 'C#CCCCCC#CC(C)C'},
    {"paper_id": '3a', "role": 'pyrone',
     "name": '2,4,5,6-tetrahydrocyclopenta[c]pyran-3(1H)-one regioisomer (bicyclic 2-pyrone from 2a + CO2)',
     "fallback_smiles": 'O=C1OC=C2CCCC2=C1'},
    {"paper_id": '3b', "role": 'pyrone',
     "name": '5,6,7,8-tetrahydro-3H-2-benzopyran-3-one (bicyclic 2-pyrone from 2b + CO2)',
     "fallback_smiles": 'O=C1OC=C2CCCCC2=C1'},
    {"paper_id": '3c', "role": 'pyrone',
     "name": '5,6,7,8-tetrahydro-1-isopropyl-3H-2-benzopyran-3-one (bicyclic 2-pyrone from 2c + CO2; iPr at C1, adjacent to ring O)',
     "fallback_smiles": 'O=C1OC(C(C)C)=C2CCCCC2=C1'},
    {"paper_id": 'Ni(cod)2', "role": 'catalyst_precursor',
     "name": 'bis(1,5-cyclooctadiene)nickel(0)',
     "fallback_smiles": '[Ni].C1CC=CCCC=C1.C1CC=CCCC=C1'},
    {"paper_id": 'cod', "role": 'ligand',
     "name": '1,5-cyclooctadiene',
     "fallback_smiles": 'C1CC=CCCC=C1'},
    {"paper_id": 'PMe3', "role": 'ligand',
     "name": 'trimethylphosphine',
     "fallback_smiles": 'CP(C)C'},
    {"paper_id": 'PEt3', "role": 'ligand',
     "name": 'triethylphosphine',
     "fallback_smiles": 'CCP(CC)CC'},
    {"paper_id": 'PBun3', "role": 'ligand',
     "name": 'tri-n-butylphosphine',
     "fallback_smiles": 'CCCCP(CCCC)CCCC'},
    {"paper_id": 'PBut3', "role": 'ligand',
     "name": 'tri-tert-butylphosphine',
     "fallback_smiles": 'CC(C)(C)P(C(C)(C)C)C(C)(C)C'},
    {"paper_id": 'PCy3', "role": 'ligand',
     "name": 'tricyclohexylphosphine',
     "fallback_smiles": 'C1CCCCC1P(C2CCCCC2)C3CCCCC3'},
    {"paper_id": 'P(C8H17-n)3', "role": 'ligand',
     "name": 'tri-n-octylphosphine',
     "fallback_smiles": 'CCCCCCCCP(CCCCCCCC)CCCCCCCC'},
    {"paper_id": 'pyridine', "role": 'ligand',
     "name": 'pyridine (additive in the Bu^n3P + pyridine 1:1 combined-ligand entry of Table 1)',
     "fallback_smiles": 'c1ccncc1'},
    {"paper_id": 'CO2', "role": 'educt',
     "name": 'carbon dioxide (cycloaddition co-substrate, contributes C=O and ring O of the 2-pyrone)',
     "fallback_smiles": 'O=C=O'},
]

EXPECTED_ELECTRONIC_STRUCTURE: dict[str, dict[str, Any]] = {
    'Ni(cod)2': {"oxidation_state": 0, "d_count": 10,
        "geometry_class": 'tetrahedral', "spin_state": 'closed_shell_singlet'},
    'Ni(1a)2_chelate': {"oxidation_state": 0, "d_count": 10,
        "geometry_class": 'tetrahedral', "spin_state": 'closed_shell_singlet'},
    'Ni(1b)2_chelate': {"oxidation_state": 0, "d_count": 10,
        "geometry_class": 'tetrahedral', "spin_state": 'closed_shell_singlet'},
}
